kk = pe
${kk} =  good
s${kk}ak =  how are you!


a:
	@echo   $(pe)
	@echo   $(speak)





m  := n
n   := p
p   := q
q   := hello 
 

b:
	@echo   $(m)
	@echo   $($(m))	
	@echo   $($($(m))) 
	@echo   $($($($(m)))) 