f =   hi
h =  
foo =  what  a  good  boy 
123 =  $$
_a =    1$$  
BB = 111
_456 = AA$$BB 
t${f}s =  20 #变量名包含变量

undefine foo 

#目标
${f}:  $(h)
	echo   $(foo) 	 
	echo   $foo
	echo   ${123}	
	echo   ${_a}
	echo   ${_456} 	
	BB=666 ; echo   ${_456} 
	echo   ${this} 

 