#隐式规则的变量
a:
	@ echo   CC是$(CC)   
	@ echo   CFLAGS是$(CFLAGS)  

	@ echo   CXX是$(CXX)
	@ echo   CXXFLAGS是$(CXXFLAGS) 	

	@ echo   FC是$(FC)
	@ echo   FFLAGS是$(FFLAGS) 	
  
	@ echo   CPP是$(CPP)
	@ echo   CPPFLAGS是$(CPPFLAGS)

	@ echo   LD是$(LD)  
	@ echo   LDFLAGS是$(LDFLAGS)	

	@ echo   AS是$(AS)
	@ echo   ASFLAGS是$(ASFLAGS)

	@ echo   AR是$(AR)  
	@ echo   ARFLAGS是$(ARFLAGS)  
	@ echo   RM是$(RM)  
 

#更改隐式规则变量的值
CC = gcc
CFLAGS = -Wall  
CPPFLAGS = -I./header
LDFLAGS  = -Lmy
LDLIBS  =-lm



#目标
main:  main.c

