#目标
a:  
	@echo  所有变量 "${.VARIABLES}"


#目标
b:	
	@ echo  解释器${MAKE} 
	@ echo  解释器版本${MAKE_VERSION}
	@ echo  make命令后的目标${MAKECMDGOALS} 
	@ echo  处理的文件列表${MAKEFILE_LIST} 	 
	@ echo  调用深度${MAKELEVEL}   

	@ echo  默认目标${.DEFAULT_GOAL}
	@ echo  配方前缀${.RECIPEPREFIX} 
	@ echo  搜索包含makefile文件的目录${.INCLUDE_DIRS} 
	@ echo  当前工作目录${CURDIR} 
	@ echo  先决条件库名的模式${.LIBPATTERNS} 

#目标
c:  
	@ echo   SHELL是${SHELL} 
	@ echo   PWD是${PWD} 
	@ echo   USER是${USER}
	@ echo   LANG是${LANG}
	@ echo   HOME是${HOME}
	@ echo   PATH是"${PATH}"  
 
